name: Continuous Integration

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    name: (Linux) Compile SourcePawn ${{matrix.sm_version}} ${{ matrix.use_optional_dependencies && '(optionals enabled)' || '(optionals disabled)' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Set up Sourcemod versions to compile against
        sm_version: ['1.11']
        use_optional_dependencies: [false, true]
        # TODO: uncomment when pipeline for backwards compatibility has been set up
        # use_backwards_compatibility: [false, true]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # TODO: see if caching could be used to speed up repeated CI/CD
      # Sets up the SourcePawn compiler
      - name: Setup SourcePawn Compiler ${{ matrix.sm_version }}
        run: |
          wget --input-file=http://sourcemod.net/smdrop/${{ matrix.sm_version }}/sourcemod-latest-linux
          tar -xzf $(cat sourcemod-latest-linux)

      - name: Fetch plugin dependencies
        run: |
          wget https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc -P addons/sourcemod/scripting/include


      # TODO: look into how complete new declare rewrites are:
      # https://raw.githubusercontent.com/JoinedSenses/SourceMod-IncludeLibrary/master/include/steamtools.inc
      # https://raw.githubusercontent.com/JoinedSenses/SourceMod-IncludeLibrary/master/include/tf2attributes.inc
      - name: Fetch optional dependencies
        if: matrix.use_optional_dependencies
        run: |
          wget https://github.com/FlaminSarge/tf2attributes/releases/download/v1.7.3/tf2attributes.inc -P addons/sourcemod/scripting/include
          wget https://raw.githubusercontent.com/asherkin/SteamTools/master/plugin/steamtools.inc -P addons/sourcemod/scripting/include
          wget https://raw.githubusercontent.com/Flyflo/SM-Goomba-Stomp/master/addons/sourcemod/scripting/include/goomba.inc -P addons/sourcemod/scripting/include
          wget https://raw.githubusercontent.com/JoinedSenses/SourceMod-IncludeLibrary/master/include/updater.inc -P addons/sourcemod/scripting/include

      - name: Compile Plugins
        run: bash $GITHUB_WORKSPACE/build.sh addons/sourcemod/scripting/spcomp 'addons/sourcemod/scripting/vsh2.sp' 'addons/sourcemod/scripting/freak_fortress_2.sp' 'addons/sourcemod/scripting/freak_fortress_2_old.sp' 'addons/sourcemod/scripting/saxtonhale.sp' -i='addons/sourcemod/scripting/include' -i='addons/sourcemod/scripting/'

      # - name: 'Upload Compilation Artifact'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: VSH2_Plugins (SM ${{ matrix.sm_version }})
      #     path: |
      #       addons/sourcemod/plugins/freak_fortress_2.smx
      #       addons/sourcemod/plugins/saxtonhale.smx
      #       addons/sourcemod/plugins/vsh2.smx

  upload_source:
    name: Upload Source
    needs: build_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Package source code
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          zip -r 'Source code.zip' ./addons
          tar cvf 'Source code.tar' addons


      # this will upload a zip with a zip and a tar file, this is to avoid being rate liited by the github API
      - name: Upload source code
        uses: actions/upload-artifact@v2
        with:
          name: VSH Source
          if-no-files-found: error
          path: |
            Source code.zip
            Source code.tar
